// MARK: - Desktop Groups
const hackerNewsDesktopGroups_DisableSocialFocus = {
  type: "checkbox",
  name: {
    ar: "تعطيل التركيز الاجتماعي على HackerNews",
    ca: "Desactiveu SocialFocus a HackerNews",
    "zh-CN": "在 HackerNews 上禁用 SocialFocus",
    "zh-TW": "在 HackerNews 上停用 SocialFocus",
    hr: "Onemogući SocialFocus na HackerNewsu",
    cs: "Zakažte SocialFocus na HackerNews",
    da: "Deaktiver SocialFocus på HackerNews",
    nl: "Schakel SocialFocus uit op HackerNews",
    en: "Disable SocialFocus on HackerNews",
    fi: "Poista SocialFocus käytöstä HackerNewsissa",
    fr: "Désactivez SocialFocus sur HackerNews",
    de: "Deaktivieren Sie SocialFocus auf HackerNews",
    el: "Απενεργοποιήστε το SocialFocus στο HackerNews",
    he: "השבת את SocialFocus ב-HackerNews",
    hi: "HackerNews पर SocialFocus अक्षम करें",
    hu: "A SocialFocus letiltása a HackerNews-on",
    id: "Nonaktifkan Fokus Sosial di HackerNews",
    it: "Disabilita SocialFocus su HackerNews",
    ja: "HackerNews で SocialFocus を無効にする",
    ko: "HackerNews에서 SocialFocus 비활성화",
    ms: "Lumpuhkan SocialFocus pada HackerNews",
    no: "Deaktiver SocialFocus på HackerNews",
    pl: "Wyłącz SocialFocus w HackerNews",
    pt: "Desative o SocialFocus no HackerNews",
    ro: "Dezactivați SocialFocus pe HackerNews",
    ru: "Отключить SocialFocus на HackerNews",
    sk: "Zakázať SocialFocus na HackerNews",
    es: "Deshabilitar SocialFocus en HackerNews",
    sv: "Inaktivera SocialFocus på HackerNews",
    th: "ปิดการใช้งาน SocialFocus บน HackerNews",
    tr: "HackerNews'te SocialFocus'u devre dışı bırakın",
    uk: "Вимкніть SocialFocus на HackerNews",
    vi: "Tắt SocialFocus trên HackerNews",
  },
  id: "socialFocus_hacker-news_master_toggle",
  defaultValue: false,
};

const hackerNewsDesktopGroups_Essentials = [
  {
    type: "checkbox",
    name: {
      ar: "كتلة هاكر نيوز",
      ca: "Bloqueja HackerNews",
      "zh-CN": "阻止黑客新闻",
      "zh-TW": "阻止駭客新聞",
      hr: "Blokiraj HackerNews",
      cs: "Blokovat HackerNews",
      da: "Bloker HackerNews",
      nl: "Blokkeer HackerNews",
      en: "Block HackerNews",
      fi: "Estä HackerNews",
      fr: "Block HackerActualités",
      de: "HackerNews blockieren",
      el: "Αποκλεισμός HackerNews",
      he: "חסום את האקרניוז",
      hi: "हैकरन्यूज को ब्लॉक करें",
      hu: "A HackerNews letiltása",
      id: "Blokir HackerNews",
      it: "Blocca HackerNews",
      ja: "ブロックハッカーニュース",
      ko: "블록해커뉴스",
      ms: "Sekat HackerNews",
      no: "Blokker HackerNews",
      pl: "Zablokuj HackerNews",
      pt: "Bloquear HackerNotícias",
      ro: "Blocați HackerNews",
      ru: "Блок ХакерНовости",
      sk: "Blokovať HackerNews",
      es: "Block HackerNoticias",
      sv: "Blockera HackerNews",
      th: "บล็อกแฮกเกอร์นิวส์",
      tr: "HackerNews'i Engelle",
      uk: "Заблокувати HackerNews",
      vi: "Chặn HackerTin tức",
    },
    id: "socialFocus_hacker-news_block_hacker-news",
    defaultValue: false,
    styles: [`html`],
  },
  {
    type: "checkbox",
    name: {
      ar: "الوضع الرمادي",
      ca: "Mode gris",
      "zh-CN": "灰度模式",
      "zh-TW": "灰階模式",
      hr: "Sivi način rada",
      cs: "Šedý režim",
      da: "Grå tilstand",
      nl: "Grijze modus",
      en: "Gray Mode",
      fi: "Harmaa tila",
      fr: "Mode gris",
      de: "Graumodus",
      el: "Γκρι λειτουργία",
      he: "מצב אפור",
      hi: "ग्रे मोड",
      hu: "Szürke mód",
      id: "Modus Abu-abu",
      it: "Modalità grigia",
      ja: "グレーモード",
      ko: "그레이 모드",
      ms: "Mod Kelabu",
      no: "Grå modus",
      pl: "Tryb szary",
      pt: "Modo cinza",
      ro: "Modul gri",
      ru: "Серый режим",
      sk: "Šedý režim",
      es: "Modo gris",
      sv: "Grått läge",
      th: "โหมดสีเทา",
      tr: "Gri Mod",
      uk: "Сірий режим",
      vi: "Chế độ màu xám",
    },
    id: "socialFocus_hacker-news_gray_mode",
    defaultValue: false,
    styles: [`html { filter: grayscale(1) !important; }`],
  },
];

const hackerNewsDesktopGroups_TimeLimit = [
  {
    type: "select",
    name: {
      ar: "الحد اليومي",
      ca: "Límit diari",
      "zh-CN": "每日限额",
      "zh-TW": "每日限額",
      hr: "Dnevni limit",
      cs: "Denní limit",
      da: "Daglig grænse",
      nl: "Dagelijkse limiet",
      en: "Daily Limit",
      fi: "Päivittäinen raja",
      fr: "Limite quotidienne",
      de: "Tageslimit",
      el: "Ημερήσιο Όριο",
      he: "מגבלה יומית",
      hi: "दैनिक सीमा",
      hu: "Napi limit",
      id: "Batas Harian",
      it: "Limite giornaliero",
      ja: "1日あたりの制限",
      ko: "일일 한도",
      ms: "Had Harian",
      no: "Daglig grense",
      pl: "Limit dzienny",
      pt: "Limite Diário",
      ro: "Limită zilnică",
      ru: "Дневной лимит",
      sk: "Denný limit",
      es: "Límite diario",
      sv: "Daglig gräns",
      th: "ขีดจำกัดรายวัน",
      tr: "Günlük Limit",
      uk: "Денний ліміт",
      vi: "Giới hạn hàng ngày",
    },
    id: "socialFocus_daily_limit",
    defaultValue: "noLimit",
    selects: [
      {
        name: {
          ar: "بلا حدود",
          ca: "Sense límits",
          "zh-CN": "没有限制",
          "zh-TW": "沒有限制",
          hr: "Bez ograničenja",
          cs: "Bez omezení",
          da: "Ingen grænser",
          nl: "Geen grenzen",
          en: "No Limits",
          fi: "Ei rajoja",
          fr: "Aucune limite",
          de: "Keine Grenzen",
          el: "Χωρίς όρια",
          he: "ללא גבולות",
          hi: "असीम",
          hu: "Nincs határ",
          id: "Tanpa Batas",
          it: "Nessun limite",
          ja: "制限なし",
          ko: "한계 없음",
          ms: "Tiada Had",
          no: "Ingen grenser",
          pl: "Bez ograniczeń",
          pt: "Sem Limites",
          ro: "Fără limite",
          ru: "Без ограничений",
          sk: "Žiadne limity",
          es: "Sin límites",
          sv: "Inga gränser",
          th: "ไม่มีขีดจำกัด",
          tr: "Sınır Yok",
          uk: "Без обмежень",
          vi: "Không có giới hạn",
        },
        id: "noLimit",
      },
    ],
  },
  {
    type: "checkbox",
    name: {
      ar: "عرض الموقت على الموقع",
      ca: "Mostra el temporitzador al lloc",
      "zh-CN": "现场显示计时器",
      "zh-TW": "現場顯示計時器",
      hr: "Prikaz mjerača vremena na licu mjesta",
      cs: "Zobrazit časovač na místě",
      da: "Vis timer på stedet",
      nl: "Timer op locatie weergeven",
      en: "Display Timer On Site",
      fi: "Näytä ajastin paikan päällä",
      fr: "Afficher la minuterie sur site",
      de: "Timer vor Ort anzeigen",
      el: "Εμφάνιση χρονοδιακόπτη στον ιστότοπο",
      he: "הצגת טיימר באתר",
      hi: "साइट पर टाइमर प्रदर्शित करें",
      hu: "Időzítő megjelenítése a helyszínen",
      id: "Tampilkan Timer Di Situs",
      it: "Visualizza il timer sul sito",
      ja: "オンサイトでタイマーを表示",
      ko: "사이트에 타이머 표시",
      ms: "Paparkan Pemasa Di Tapak",
      no: "Vis timer på stedet",
      pl: "Wyświetl timer na miejscu",
      pt: "Exibir temporizador no local",
      ro: "Afișează cronometrul la fața locului",
      ru: "Отображение таймера на месте",
      sk: "Zobraziť časovač na mieste",
      es: "Mostrar temporizador en el sitio",
      sv: "Visa timer på plats",
      th: "แสดงตัวจับเวลาบนเว็บไซต์",
      tr: "Zamanlayıcıyı Sitede Görüntüle",
      uk: "Відображення таймера на сайті",
      vi: "Hiển thị bộ đếm thời gian trên trang web",
    },
    id: "socialFocus_hacker-news_daily_limit_show_timer_draggable",
    defaultValue: false,
  },
];

const hackerNewsDesktopGroups_Navigation = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'جديد'",
      ca: "Amaga 'Nou'",
      "zh-CN": "隐藏“新”",
      "zh-TW": "隱藏“新”",
      hr: "Sakrij 'Novo'",
      cs: "Skrýt 'Nové'",
      da: "Skjul 'Ny'",
      nl: "Verberg 'Nieuw'",
      en: "Hide 'New'",
      fi: "Piilota 'Uusi'",
      fr: "Masquer 'Nouveau'",
      de: "„Neu“ ausblenden",
      el: "Απόκρυψη 'Νέου'",
      he: "הסתר 'חדש'",
      hi: "'नया' छुपाएं",
      hu: "'Új' elrejtése",
      id: "Sembunyikan 'Baru'",
      it: "Nascondi 'Nuovo'",
      ja: "「新規」を隠す",
      ko: "'신규' 숨기기",
      ms: "Sembunyikan 'Baharu'",
      no: "Skjul 'Ny'",
      pl: "Ukryj „Nowy”",
      pt: "Ocultar 'Novo'",
      ro: "Ascunde „Nou”",
      ru: "Скрыть «Новое»",
      sk: "Skryť 'Nové'",
      es: "Ocultar 'Nuevo'",
      sv: "Göm 'Ny'",
      th: "ซ่อน 'ใหม่'",
      tr: "'Yeni'yi gizle",
      uk: "Сховати 'Новий'",
      vi: "Ẩn 'Mới'",
    },
    id: "socialFocus_hacker-news_navigation_hide_new",
    defaultValue: false,
    styles: [`a[href="newest"]`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'الماضي'",
      ca: "Amaga 'Passat'",
      "zh-CN": "隐藏“过去”",
      "zh-TW": "隱藏“過去”",
      hr: "Sakrij 'Prošlost'",
      cs: "Skrýt 'minulost'",
      da: "Skjul 'fortid'",
      nl: "Verberg 'Verleden'",
      en: "Hide 'Past'",
      fi: "Piilota 'menneisyys'",
      fr: "Masquer 'Passé'",
      de: "„Vergangenheit“ ausblenden",
      el: "Απόκρυψη 'Παρελθόν'",
      he: "הסתר 'עבר'",
      hi: "'अतीत' छिपाएँ",
      hu: "'Múlt' elrejtése",
      id: "Sembunyikan 'Masa Lalu'",
      it: "Nascondi 'Passato'",
      ja: "「過去」を隠す",
      ko: "'과거' 숨기기",
      ms: "Sembunyikan 'Lalu'",
      no: "Skjul 'Fortid'",
      pl: "Ukryj „przeszłość”",
      pt: "Ocultar 'Passado'",
      ro: "Ascunde „Trecut”",
      ru: "Скрыть «Прошлое»",
      sk: "Skryť 'minulosť'",
      es: "Ocultar 'Pasado'",
      sv: "Göm 'förflutna'",
      th: "ซ่อน 'อดีต'",
      tr: "'Geçmiş'i gizle",
      uk: "Приховати 'Минуле'",
      vi: "Ẩn 'Quá khứ'",
    },
    id: "socialFocus_hacker-news_navigation_hide_past",
    defaultValue: false,
    styles: [`a[href="front"]`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'التعليقات'",
      ca: "Amaga 'Comentaris'",
      "zh-CN": "隐藏“评论”",
      "zh-TW": "隱藏“評論”",
      hr: "Sakrij 'Komentare'",
      cs: "Skrýt 'Komentáře'",
      da: "Skjul 'Kommentarer'",
      nl: "Verberg 'Opmerkingen'",
      en: "Hide 'Comments'",
      fi: "Piilota 'kommentit'",
      fr: "Masquer les 'Commentaires'",
      de: "„Kommentare“ ausblenden",
      el: "Απόκρυψη 'Σχόλια'",
      he: "הסתר 'תגובות'",
      hi: "'टिप्पणियाँ' छिपाएँ",
      hu: "'Megjegyzések' elrejtése",
      id: "Sembunyikan 'Komentar'",
      it: "Nascondi 'Commenti'",
      ja: "「コメント」を非表示にする",
      ko: "'댓글' 숨기기",
      ms: "Sembunyikan 'Ulasan'",
      no: "Skjul 'Kommentarer'",
      pl: "Ukryj „Komentarze”",
      pt: "Ocultar 'Comentários'",
      ro: "Ascunde „Comentarii”",
      ru: "Скрыть «Комментарии»",
      sk: "Skryť 'Komentáre'",
      es: "Ocultar 'Comentarios'",
      sv: "Dölj 'Kommentarer'",
      th: "ซ่อน 'ความคิดเห็น'",
      tr: "'Yorumlar'ı gizle",
      uk: "Приховати 'Коментарі'",
      vi: "Ẩn 'Bình luận'",
    },
    id: "socialFocus_hacker-news_navigation_hide_comments",
    defaultValue: false,
    styles: [`a[href="newcomments"]`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'اسأل'",
      ca: "Amaga 'Preguntar'",
      "zh-CN": "隐藏“询问”",
      "zh-TW": "隱藏“詢問”",
      hr: "Sakrij 'Pitaj'",
      cs: "Skrýt 'Zeptejte se'",
      da: "Skjul 'Spørg'",
      nl: "Verberg 'Vraag'",
      en: "Hide 'Ask'",
      fi: "Piilota 'Kysy'",
      fr: "Masquer 'Demander'",
      de: "„Fragen“ ausblenden",
      el: "Απόκρυψη 'Ρωτήστε'",
      he: "הסתר 'שאל'",
      hi: "'पूछें' छुपाएं",
      hu: "„Kérdés” elrejtése",
      id: "Sembunyikan 'Tanya'",
      it: "Nascondi 'Chiedi'",
      ja: "「質問」を非表示にする",
      ko: "'질문' 숨기기",
      ms: "Sembunyikan 'Tanya'",
      no: "Skjul 'Spør'",
      pl: "Ukryj „Zapytaj”",
      pt: "Ocultar 'Perguntar'",
      ro: "Ascunde „Întreabă”",
      ru: "Скрыть «Спросить»",
      sk: "Skryť 'Spýtať sa'",
      es: "Ocultar 'Preguntar'",
      sv: "Dölj 'Fråga'",
      th: "ซ่อน 'ถาม'",
      tr: "'Sor'u gizle",
      uk: "Сховати 'Запитати'",
      vi: "Ẩn 'Hỏi'",
    },
    id: "socialFocus_hacker-news_navigation_hide_ask",
    defaultValue: false,
    styles: [`a[href="ask"]`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'إظهار'",
      ca: "Amaga 'Mostra'",
      "zh-CN": "隐藏“显示”",
      "zh-TW": "隱藏“顯示”",
      hr: "Sakrij 'Prikaži'",
      cs: "Skrýt 'Zobrazit'",
      da: "Skjul 'Vis'",
      nl: "Verberg 'Toon'",
      en: "Hide 'Show'",
      fi: "Piilota 'Näytä'",
      fr: "Masquer 'Afficher'",
      de: "Ausblenden „Anzeigen“",
      el: "Απόκρυψη 'Εμφάνιση'",
      he: "הסתר 'הצג'",
      hi: "छिपाएं दिखाएं'",
      hu: "'Megjelenítés' elrejtése",
      id: "Sembunyikan 'Tampilkan'",
      it: "Nascondi 'Mostra'",
      ja: "「表示」を隠す",
      ko: "'표시' 숨기기",
      ms: "Sembunyikan 'Tunjukkan'",
      no: "Skjul 'Vis'",
      pl: "Ukryj „Pokaż”",
      pt: "Ocultar 'Mostrar'",
      ro: "Ascunde „Afișează”",
      ru: "Скрыть «Показать»",
      sk: "Skryť 'Zobraziť'",
      es: "Ocultar 'Mostrar'",
      sv: "Dölj 'Visa'",
      th: "ซ่อน 'แสดง'",
      tr: "'Göster'i gizle",
      uk: "Сховати 'Показати'",
      vi: "Ẩn 'Hiển thị'",
    },
    id: "socialFocus_hacker-news_navigation_hide_show",
    defaultValue: false,
    styles: [`a[href="show"]`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'الوظائف'",
      ca: "Amaga 'Ocupacions'",
      "zh-CN": "隐藏“职位”",
      "zh-TW": "隱藏“職位”",
      hr: "Sakrij 'Poslove'",
      cs: "Skrýt 'Zaměstnání'",
      da: "Skjul 'Jobs'",
      nl: "Verberg 'Vacatures'",
      en: "Hide 'Jobs'",
      fi: "Piilota 'Työt'",
      fr: "Masquer les « Emplois »",
      de: "„Jobs“ ausblenden",
      el: "Απόκρυψη 'Εργασίες'",
      he: "הסתר 'עבודות'",
      hi: "'नौकरियाँ' छिपाएँ",
      hu: "'Munkák' elrejtése",
      id: "Sembunyikan 'Pekerjaan'",
      it: "Nascondi 'Lavori'",
      ja: "「ジョブ」を非表示にする",
      ko: "'채용정보' 숨기기",
      ms: "Sembunyikan 'Pekerjaan'",
      no: "Skjul 'Jobber'",
      pl: "Ukryj „Pracę”",
      pt: "Ocultar 'Trabalhos'",
      ro: "Ascundeți „Locuri de muncă”",
      ru: "Скрыть «Вакансии»",
      sk: "Skryť 'Úlohy'",
      es: "Ocultar 'Trabajos'",
      sv: "Dölj 'Jobb'",
      th: "ซ่อน 'งาน'",
      tr: "'İşler'i gizle",
      uk: "Приховати 'Вакансії'",
      vi: "Ẩn 'Việc làm'",
    },
    id: "socialFocus_hacker-news_navigation_hide_jobs",
    defaultValue: false,
    styles: [`a[href="jobs"]`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'إرسال'",
      ca: "Amaga 'Envia'",
      "zh-CN": "隐藏“提交”",
      "zh-TW": "隱藏“提交”",
      hr: "Sakrij 'Pošalji'",
      cs: "Skrýt 'Odeslat'",
      da: "Skjul 'Send'",
      nl: "Verberg 'Verzenden'",
      en: "Hide 'Submit'",
      fi: "Piilota 'Lähetä'",
      fr: "Masquer 'Envoyer'",
      de: "„Senden“ ausblenden",
      el: "Απόκρυψη 'Υποβολή'",
      he: "הסתר 'שלח'",
      hi: "'सबमिट करें' छुपाएं",
      hu: "„Küldés” elrejtése",
      id: "Sembunyikan 'Kirim'",
      it: "Nascondi 'Invia'",
      ja: "「送信」を非表示にする",
      ko: "'제출' 숨기기",
      ms: "Sembunyikan 'Serah'",
      no: "Skjul 'Send inn'",
      pl: "Ukryj „Prześlij”",
      pt: "Ocultar 'Enviar'",
      ro: "Ascunde „Trimite”",
      ru: "Скрыть «Отправить»",
      sk: "Skryť 'Odoslať'",
      es: "Ocultar 'Enviar'",
      sv: "Dölj 'Skicka'",
      th: "ซ่อน 'ส่ง'",
      tr: "'Gönder'i gizle",
      uk: "Сховати 'Надіслати'",
      vi: "Ẩn 'Gửi'",
    },
    id: "socialFocus_hacker-news_navigation_hide_submit",
    defaultValue: false,
    styles: [`a[href="submit"]`],
  },
];

const hackerNewsDesktopGroups_Post = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء المجال",
      ca: "Amaga el domini",
      "zh-CN": "隐藏域名",
      "zh-TW": "隱藏域名",
      hr: "Sakrij domenu",
      cs: "Skrýt doménu",
      da: "Skjul domæne",
      nl: "Domein verbergen",
      en: "Hide Domain",
      fi: "Piilota verkkotunnus",
      fr: "Masquer le domaine",
      de: "Domäne ausblenden",
      el: "Απόκρυψη τομέα",
      he: "הסתר דומיין",
      hi: "डोमेन छिपाएँ",
      hu: "Domain elrejtése",
      id: "Sembunyikan Domain",
      it: "Nascondi dominio",
      ja: "ドメインを隠す",
      ko: "도메인 숨기기",
      ms: "Sembunyikan Domain",
      no: "Skjul domene",
      pl: "Ukryj domenę",
      pt: "Ocultar domínio",
      ro: "Ascunde domeniul",
      ru: "Скрыть домен",
      sk: "Skryť doménu",
      es: "Ocultar dominio",
      sv: "Dölj domän",
      th: "ซ่อนโดเมน",
      tr: "Alanı Gizle",
      uk: "Приховати домен",
      vi: "Ẩn tên miền",
    },
    id: "socialFocus_hacker-news_post_hide_domain",
    defaultValue: false,
    styles: [`html::not(:has(table.comment-tree)) span.sitebit.comhead`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'التصويت'",
      ca: "Amaga el botó 'Vota'",
      "zh-CN": "隐藏“投票”按钮",
      "zh-TW": "隱藏“投票”按鈕",
      hr: "Sakrij gumb 'Glasaj'",
      cs: "Skrýt tlačítko „Hlasovat“",
      da: "Skjul 'Stem'-knap",
      nl: "Knop 'Stem' verbergen",
      en: "Hide 'Vote' Button",
      fi: "Piilota Äänestyspainike",
      fr: "Masquer le bouton « Voter »",
      de: "Schaltfläche „Abstimmen“ ausblenden",
      el: "Απόκρυψη του κουμπιού «ψηφοφορία»",
      he: "הסתר את כפתור 'הצבע'",
      hi: "'वोट' बटन छिपाएँ",
      hu: "A „Szavazás” gomb elrejtése",
      id: "Sembunyikan Tombol 'Pilih'",
      it: "Nascondi il pulsante 'Vota'",
      ja: "「投票」ボタンを非表示にする",
      ko: "'투표' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Undi'",
      no: "Skjul Stem-knappen",
      pl: "Ukryj przycisk „Głosuj”",
      pt: "Ocultar botão 'Votar'",
      ro: "Ascundeți butonul „Votați”",
      ru: "Скрыть кнопку «Голосовать»",
      sk: "Skryť tlačidlo „Hlasovať“",
      es: "Ocultar el botón 'Votar'",
      sv: "Dölj 'Rösta'-knappen",
      th: "ซ่อนปุ่ม 'โหวต'",
      tr: "'Oy Ver' Düğmesini Gizle",
      uk: "Сховати кнопку «Голосувати»",
      vi: "Ẩn nút 'Bình chọn'",
    },
    id: "socialFocus_hacker-news_post_hide_vote_button",
    defaultValue: false,
    styles: [
      `html::not(:has(table.comment-tree)) td.votelinks a[href*="vote"]`,
      `html::not(:has(table.comment-tree)) td.votelinks { width: 14px !important; height: 19px !important; }`,
    ],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'إخفاء'",
      ca: "Amaga el botó 'Oculta'",
      "zh-CN": "隐藏“隐藏”按钮",
      "zh-TW": "隱藏“隱藏”按鈕",
      hr: "Sakrij gumb 'Sakrij'",
      cs: "Skrýt tlačítko 'Skrýt'",
      da: "Skjul 'Skjul'-knap",
      nl: "Knop 'Verbergen' verbergen",
      en: "Hide 'Hide' Button",
      fi: "Piilota Piilota-painike",
      fr: "Masquer le bouton « Masquer »",
      de: "Schaltfläche „Ausblenden“ ausblenden",
      el: "Κουμπί απόκρυψης 'Απόκρυψη'",
      he: "הסתר כפתור 'הסתר'",
      hi: "'छिपाएँ' बटन छिपाएँ",
      hu: "Az „Elrejtés” gomb elrejtése",
      id: "Sembunyikan Tombol 'Sembunyikan'",
      it: "Nascondi il pulsante 'Nascondi'",
      ja: "「非表示」ボタンを非表示にする",
      ko: "'숨기기' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Sembunyikan'",
      no: "Skjul 'Skjul'-knappen",
      pl: "Ukryj przycisk „Ukryj”",
      pt: "Ocultar botão 'Ocultar'",
      ro: "Ascunde butonul „Ascunde”",
      ru: "Скрыть кнопку «Скрыть»",
      sk: "Skryť tlačidlo „Skryť“",
      es: "Ocultar el botón 'Ocultar'",
      sv: "Göm 'Göm'-knappen",
      th: "ซ่อนปุ่ม 'ซ่อน'",
      tr: "'Gizle' Düğmesini Gizle",
      uk: "Приховати кнопку «Приховати»",
      vi: "Ẩn nút 'Ẩn'",
    },
    id: "socialFocus_hacker-news_post_hide_hide_button",
    defaultValue: false,
    styles: [`html::not(:has(table.comment-tree)) td.subtext a[href*="hide"]`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء عدد النقاط",
      ca: "Amaga el recompte de punts",
      "zh-CN": "隐藏点数",
      "zh-TW": "隱藏點數",
      hr: "Sakrij broj bodova",
      cs: "Skrýt počet bodů",
      da: "Skjul antal point",
      nl: "Puntentelling verbergen",
      en: "Hide Points Count",
      fi: "Piilota pisteiden määrä",
      fr: "Masquer le décompte des points",
      de: "Punkteanzahl ausblenden",
      el: "Απόκρυψη καταμέτρησης πόντων",
      he: "הסתר ספירת נקודות",
      hi: "अंक गिनती छिपाएँ",
      hu: "Pontszám elrejtése",
      id: "Sembunyikan Jumlah Poin",
      it: "Nascondi conteggio punti",
      ja: "ポイント数を非表示にする",
      ko: "포인트 수 숨기기",
      ms: "Sembunyikan Kiraan Mata",
      no: "Skjul antall poeng",
      pl: "Ukryj liczbę punktów",
      pt: "Ocultar contagem de pontos",
      ro: "Ascunde numărul de puncte",
      ru: "Скрыть подсчет очков",
      sk: "Skryť počet bodov",
      es: "Ocultar recuento de puntos",
      sv: "Göm antal poäng",
      th: "ซ่อนการนับคะแนน",
      tr: "Puan Sayısını Gizle",
      uk: "Приховати кількість балів",
      vi: "Ẩn số điểm",
    },
    id: "socialFocus_hacker-news_post_hide_points_count",
    defaultValue: false,
    styles: [`html::not(:has(table.comment-tree)) td.subtext span.score`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء الوقت",
      ca: "Amaga el temps",
      "zh-CN": "隐藏时间",
      "zh-TW": "隱藏時間",
      hr: "Sakrij vrijeme",
      cs: "Skrýt čas",
      da: "Skjul tid",
      nl: "Tijd verbergen",
      en: "Hide Time",
      fi: "Piilota aika",
      fr: "Masquer l'heure",
      de: "Zeit ausblenden",
      el: "Απόκρυψη χρόνου",
      he: "הסתר זמן",
      hi: "समय छिपाएँ",
      hu: "Idő elrejtése",
      id: "Sembunyikan Waktu",
      it: "Nascondi tempo",
      ja: "時間を隠す",
      ko: "시간 숨기기",
      ms: "Sembunyikan Masa",
      no: "Skjul tid",
      pl: "Ukryj czas",
      pt: "Ocultar tempo",
      ro: "Ascunde Timpul",
      ru: "Скрыть время",
      sk: "Skryť čas",
      es: "Ocultar hora",
      sv: "Göm tid",
      th: "ซ่อนเวลา",
      tr: "Zamanı Gizle",
      uk: "Приховати час",
      vi: "Ẩn thời gian",
    },
    id: "socialFocus_hacker-news_post_hide_time",
    defaultValue: false,
    styles: [`html::not(:has(table.comment-tree)) span.age`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'التعليقات'",
      ca: "Amaga el botó 'Comentaris'",
      "zh-CN": "隐藏“评论”按钮",
      "zh-TW": "隱藏“評論”按鈕",
      hr: "Sakrij gumb 'Komentari'",
      cs: "Skrýt tlačítko 'Komentáře'",
      da: "Skjul knappen 'Kommentarer'",
      nl: "Knop 'Opmerkingen' verbergen",
      en: "Hide 'Comments' Button",
      fi: "Piilota Kommentit-painike",
      fr: "Masquer le bouton « Commentaires »",
      de: "Schaltfläche „Kommentare“ ausblenden",
      el: "Κουμπί απόκρυψη «Σχόλια»",
      he: "הסתר את לחצן 'הערות'",
      hi: "'टिप्पणियाँ' बटन छिपाएँ",
      hu: "A 'Megjegyzések' gomb elrejtése",
      id: "Sembunyikan Tombol 'Komentar'",
      it: "Nascondi il pulsante 'Commenti'",
      ja: "「コメント」ボタンを非表示にする",
      ko: "'댓글' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Ulasan'",
      no: "Skjul 'Kommentarer'-knappen",
      pl: "Ukryj przycisk „Komentarze”",
      pt: "Ocultar botão 'Comentários'",
      ro: "Ascundeți butonul „Comentarii”",
      ru: "Скрыть кнопку «Комментарии»",
      sk: "Skryť tlačidlo 'Komentáre'",
      es: "Ocultar el botón 'Comentarios'",
      sv: "Dölj knappen 'Kommentarer'",
      th: "ซ่อนปุ่ม 'ความคิดเห็น'",
      tr: "'Yorumlar' Düğmesini Gizle",
      uk: "Приховати кнопку «Коментарі»",
      vi: "Ẩn nút 'Nhận xét'",
    },
    id: "socialFocus_hacker-news_post_hide_comments_button",
    defaultValue: false,
    styles: [
      `html::not(:has(table.comment-tree)) td.subtext span.subline > a:last-of-type`,
    ],
  },
];

const hackerNewsDesktopGroups_Comments = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء التعليقات",
      ca: "Amaga els comentaris",
      "zh-CN": "隐藏评论",
      "zh-TW": "隱藏評論",
      hr: "Sakrij komentare",
      cs: "Skrýt komentáře",
      da: "Skjul kommentarer",
      nl: "Opmerkingen verbergen",
      en: "Hide Comments",
      fi: "Piilota kommentit",
      fr: "Masquer les commentaires",
      de: "Kommentare ausblenden",
      el: "Απόκρυψη σχολίων",
      he: "הסתר הערות",
      hi: "टिप्पणियाँ छिपाएँ",
      hu: "Megjegyzések elrejtése",
      id: "Sembunyikan Komentar",
      it: "Nascondi commenti",
      ja: "コメントを隠す",
      ko: "댓글 숨기기",
      ms: "Sembunyikan Komen",
      no: "Skjul kommentarer",
      pl: "Ukryj komentarze",
      pt: "Ocultar comentários",
      ro: "Ascunde comentariile",
      ru: "Скрыть комментарии",
      sk: "Skryť komentáre",
      es: "Ocultar comentarios",
      sv: "Dölj kommentarer",
      th: "ซ่อนความคิดเห็น",
      tr: "Yorumları Gizle",
      uk: "Приховати коментарі",
      vi: "Ẩn bình luận",
    },
    id: "socialFocus_hacker-news_comments_hide_comments",
    defaultValue: false,
    styles: [`table.comment-tree`],
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء أزرار 'الرد'",
      ca: "Amaga els botons 'Resposta'",
      "zh-CN": "隐藏“回复”按钮",
      "zh-TW": "隱藏「回覆」按鈕",
      hr: "Sakrij gumbe 'Odgovori'",
      cs: "Skrýt tlačítka „Odpovědět“",
      da: "Skjul 'Svar'-knapper",
      nl: "Verberg de 'Beantwoord'-knoppen",
      en: "Hide 'Reply' Buttons",
      fi: "Piilota Vastaa-painikkeet",
      fr: "Masquer les boutons « Répondre »",
      de: "Schaltflächen „Antworten“ ausblenden",
      el: "Απόκρυψη κουμπιών «Απάντηση»",
      he: "הסתר את לחצני 'השב'",
      hi: "'उत्तर' बटन छिपाएँ",
      hu: "A „Válasz” gombok elrejtése",
      id: "Sembunyikan Tombol 'Balas'",
      it: "Nascondi i pulsanti 'Rispondi'",
      ja: "「返信」ボタンを非表示にする",
      ko: "'답장' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Balas'",
      no: "Skjul 'Svar'-knapper",
      pl: "Ukryj przyciski „Odpowiedz”",
      pt: "Ocultar botões de ‘Responder’",
      ro: "Ascundeți butoanele „Răspuns”",
      ru: "Скрыть кнопки «Ответить»",
      sk: "Skryť tlačidlá „Odpovedať“",
      es: "Ocultar botones 'Responder'",
      sv: "Dölj 'Svara'-knappar",
      th: "ซ่อนปุ่ม 'ตอบกลับ'",
      tr: "'Yanıtla' Düğmelerini Gizle",
      uk: "Сховати кнопки «Відповісти»",
      vi: "Ẩn nút 'Trả lời'",
    },
    id: "socialFocus_hacker-news_comments_hide_reply_buttons",
    defaultValue: false,
    styles: [`div.reply`],
  },
];

// MARK: - Desktop Builder

const hackerNewsDesktopGroups = [
  {
    groupName: {
      ar: "",
      ca: "",
      "zh-CN": "",
      "zh-TW": "",
      hr: "",
      cs: "",
      da: "",
      nl: "",
      en: "",
      fi: "",
      fr: "",
      de: "",
      el: "",
      he: "",
      hi: "",
      hu: "",
      id: "",
      it: "",
      ja: "",
      ko: "",
      ms: "",
      no: "",
      pl: "",
      pt: "",
      ro: "",
      ru: "",
      sk: "",
      es: "",
      sv: "",
      th: "",
      tr: "",
      uk: "",
      vi: "",
    },
    groupId: "disableSocialFocus",
    parentCategoryId: "hackerNews",
    options: [hackerNewsDesktopGroups_DisableSocialFocus],
  },
  {
    groupName: {
      ar: "أساسيات",
      ca: "Essencials",
      "zh-CN": "必需品",
      "zh-TW": "必需品",
      hr: "Osnove",
      cs: "Essentials",
      da: "Essentialer",
      nl: "Essentiële zaken",
      en: "Essentials",
      fi: "Essentials",
      fr: "Essentiel",
      de: "Wesentliches",
      el: "Βασικά",
      he: "יסודות",
      hi: "अनिवार्य",
      hu: "Essentials",
      id: "Penting",
      it: "Elementi essenziali",
      ja: "必需品",
      ko: "골자",
      ms: "Perkara-perkara penting",
      no: "Essensielle",
      pl: "Elementy zasadnicze",
      pt: "Fundamentos",
      ro: "Esențiale",
      ru: "Основы",
      sk: "Essentials",
      es: "Esenciales",
      sv: "Essentials",
      th: "สิ่งจำเป็น",
      tr: "Temeller",
      uk: "Основи",
      vi: "Yếu tố cần thiết",
    },
    groupId: "essentials",
    parentCategoryId: "hackerNews",
    options: hackerNewsDesktopGroups_Essentials,
  },
  {
    groupName: {
      ar: "الحد الزمني",
      ca: "Límit de temps",
      "zh-CN": "时限",
      "zh-TW": "時限",
      hr: "Vremensko ograničenje",
      cs: "Časový limit",
      da: "Tidsgrænse",
      nl: "Tijdslimiet",
      en: "Time Limit",
      fi: "Määräaika",
      fr: "Limite de temps",
      de: "Zeitlimit",
      el: "Προθεσμία",
      he: "מגבלת זמן",
      hi: "समय सीमा",
      hu: "Időkorlát",
      id: "Batas waktu",
      it: "Limite di tempo",
      ja: "期限",
      ko: "시간 제한",
      ms: "Had Masa",
      no: "Tidsbegrensning",
      pl: "Limit czasu",
      pt: "Limite de tempo",
      ro: "Limită de timp",
      ru: "Лимит времени",
      sk: "Časový limit",
      es: "Límite de tiempo",
      sv: "Tidsgräns",
      th: "จำกัดเวลา",
      tr: "Zaman Sınırı",
      uk: "Обмеження часу",
      vi: "Giới hạn thời gian",
    },
    groupId: "timeLimit",
    parentCategoryId: "hackerNews",
    options: hackerNewsDesktopGroups_TimeLimit,
  },
  {
    groupName: {
      ar: "ملاحة",
      ca: "Navegació",
      "zh-CN": "导航",
      "zh-TW": "導航",
      hr: "Navigacija",
      cs: "Navigace",
      da: "Navigation",
      nl: "Navigatie",
      en: "Navigation",
      fi: "Navigointi",
      fr: "Navigation",
      de: "Navigation",
      el: "Πλοήγηση",
      he: "ניווט",
      hi: "मार्गदर्शन",
      hu: "Navigáció",
      id: "Navigasi",
      it: "Navigazione",
      ja: "ナビゲーション",
      ko: "항해",
      ms: "Navigasi",
      no: "Navigasjon",
      pl: "Nawigacja",
      pt: "Navegação",
      ro: "Navigare",
      ru: "Навигация",
      sk: "Navigácia",
      es: "Navegación",
      sv: "Navigering",
      th: "การนำทาง",
      tr: "Navigasyon",
      uk: "Навігація",
      vi: "Điều hướng",
    },
    groupId: "navigation",
    parentCategoryId: "hacker-news",
    options: hackerNewsDesktopGroups_Navigation,
  },
  {
    groupName: {
      ar: "دعامات",
      ca: "Publicacions",
      "zh-CN": "帖子",
      "zh-TW": "貼文",
      hr: "Postovi",
      cs: "Příspěvky",
      da: "Indlæg",
      nl: "Berichten",
      en: "Posts",
      fi: "Viestit",
      fr: "Des postes",
      de: "Beiträge",
      el: "Αναρτήσεις",
      he: "פוסטים",
      hi: "पदों",
      hu: "Hozzászólások",
      id: "Postingan",
      it: "Messaggi",
      ja: "投稿",
      ko: "게시물",
      ms: "Catatan",
      no: "Innlegg",
      pl: "Posty",
      pt: "Postagens",
      ro: "Postări",
      ru: "Сообщения",
      sk: "Príspevky",
      es: "Publicaciones",
      sv: "Inlägg",
      th: "กระทู้",
      tr: "Gönderiler",
      uk: "Пости",
      vi: "Bài viết",
    },
    groupId: "post",
    parentCategoryId: "hacker-news",
    options: hackerNewsDesktopGroups_Post,
  },
  {
    groupName: {
      ar: "صفحة التعليقات",
      ca: "Pàgina de comentaris",
      "zh-CN": "评论页",
      "zh-TW": "評論頁",
      hr: "Stranica s komentarima",
      cs: "Stránka s komentáři",
      da: "Kommentarside",
      nl: "Opmerkingenpagina",
      en: "Comments Page",
      fi: "Kommentit-sivu",
      fr: "Page de commentaires",
      de: "Kommentarseite",
      el: "Σελίδα σχολίων",
      he: "עמוד תגובות",
      hi: "टिप्पणियाँ पृष्ठ",
      hu: "Megjegyzések oldal",
      id: "Halaman Komentar",
      it: "Pagina dei commenti",
      ja: "コメントページ",
      ko: "댓글 페이지",
      ms: "Halaman Komen",
      no: "Kommentarside",
      pl: "Strona z komentarzami",
      pt: "Página de comentários",
      ro: "Pagina de comentarii",
      ru: "Страница комментариев",
      sk: "Stránka s komentármi",
      es: "Página de comentarios",
      sv: "Kommentarssida",
      th: "หน้าความคิดเห็น",
      tr: "Yorumlar Sayfası",
      uk: "Сторінка коментарів",
      vi: "Trang bình luận",
    },
    groupId: "comments-page",
    parentCategoryId: "hacker-news",
    options: hackerNewsDesktopGroups_Comments,
  },
];

// MARK: - Mobile Groups
const hackerNewsMobileGroups_DisableSocialFocus = {
  type: "checkbox",
  name: {
    ar: "تعطيل التركيز الاجتماعي على HackerNews",
    ca: "Desactiveu SocialFocus a HackerNews",
    "zh-CN": "在 HackerNews 上禁用 SocialFocus",
    "zh-TW": "在 HackerNews 上停用 SocialFocus",
    hr: "Onemogući SocialFocus na HackerNewsu",
    cs: "Zakažte SocialFocus na HackerNews",
    da: "Deaktiver SocialFocus på HackerNews",
    nl: "Schakel SocialFocus uit op HackerNews",
    en: "Disable SocialFocus on HackerNews",
    fi: "Poista SocialFocus käytöstä HackerNewsissa",
    fr: "Désactivez SocialFocus sur HackerNews",
    de: "Deaktivieren Sie SocialFocus auf HackerNews",
    el: "Απενεργοποιήστε το SocialFocus στο HackerNews",
    he: "השבת את SocialFocus ב-HackerNews",
    hi: "HackerNews पर SocialFocus अक्षम करें",
    hu: "A SocialFocus letiltása a HackerNews-on",
    id: "Nonaktifkan Fokus Sosial di HackerNews",
    it: "Disabilita SocialFocus su HackerNews",
    ja: "HackerNews で SocialFocus を無効にする",
    ko: "HackerNews에서 SocialFocus 비활성화",
    ms: "Lumpuhkan SocialFocus pada HackerNews",
    no: "Deaktiver SocialFocus på HackerNews",
    pl: "Wyłącz SocialFocus w HackerNews",
    pt: "Desative o SocialFocus no HackerNews",
    ro: "Dezactivați SocialFocus pe HackerNews",
    ru: "Отключить SocialFocus на HackerNews",
    sk: "Zakázať SocialFocus na HackerNews",
    es: "Deshabilitar SocialFocus en HackerNews",
    sv: "Inaktivera SocialFocus på HackerNews",
    th: "ปิดการใช้งาน SocialFocus บน HackerNews",
    tr: "HackerNews'te SocialFocus'u devre dışı bırakın",
    uk: "Вимкніть SocialFocus на HackerNews",
    vi: "Tắt SocialFocus trên HackerNews",
  },
  id: "socialFocus_hacker-news_master_toggle",
  defaultValue: false,
};

const hackerNewsMobileGroups_Essentials = [
  {
    type: "checkbox",
    name: {
      ar: "كتلة هاكر نيوز",
      ca: "Bloqueja HackerNews",
      "zh-CN": "阻止黑客新闻",
      "zh-TW": "阻止駭客新聞",
      hr: "Blokiraj HackerNews",
      cs: "Blokovat HackerNews",
      da: "Bloker HackerNews",
      nl: "Blokkeer HackerNews",
      en: "Block HackerNews",
      fi: "Estä HackerNews",
      fr: "Block HackerActualités",
      de: "HackerNews blockieren",
      el: "Αποκλεισμός HackerNews",
      he: "חסום את האקרניוז",
      hi: "हैकरन्यूज को ब्लॉक करें",
      hu: "A HackerNews letiltása",
      id: "Blokir HackerNews",
      it: "Blocca HackerNews",
      ja: "ブロックハッカーニュース",
      ko: "블록해커뉴스",
      ms: "Sekat HackerNews",
      no: "Blokker HackerNews",
      pl: "Zablokuj HackerNews",
      pt: "Bloquear HackerNotícias",
      ro: "Blocați HackerNews",
      ru: "Блок ХакерНовости",
      sk: "Blokovať HackerNews",
      es: "Block HackerNoticias",
      sv: "Blockera HackerNews",
      th: "บล็อกแฮกเกอร์นิวส์",
      tr: "HackerNews'i Engelle",
      uk: "Заблокувати HackerNews",
      vi: "Chặn HackerTin tức",
    },
    id: "socialFocus_hacker-news_block_gmail",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "الوضع الرمادي",
      ca: "Mode gris",
      "zh-CN": "灰度模式",
      "zh-TW": "灰階模式",
      hr: "Sivi način rada",
      cs: "Šedý režim",
      da: "Grå tilstand",
      nl: "Grijze modus",
      en: "Gray Mode",
      fi: "Harmaa tila",
      fr: "Mode gris",
      de: "Graumodus",
      el: "Γκρι λειτουργία",
      he: "מצב אפור",
      hi: "ग्रे मोड",
      hu: "Szürke mód",
      id: "Modus Abu-abu",
      it: "Modalità grigia",
      ja: "グレーモード",
      ko: "그레이 모드",
      ms: "Mod Kelabu",
      no: "Grå modus",
      pl: "Tryb szary",
      pt: "Modo cinza",
      ro: "Modul gri",
      ru: "Серый режим",
      sk: "Šedý režim",
      es: "Modo gris",
      sv: "Grått läge",
      th: "โหมดสีเทา",
      tr: "Gri Mod",
      uk: "Сірий режим",
      vi: "Chế độ màu xám",
    },
    id: "socialFocus_hacker-news_gray_mode",
    defaultValue: false,
  },
];

const hackerNewsMobileGroups_TimeLimit = [
  {
    type: "select",
    name: {
      ar: "الحد اليومي",
      ca: "Límit diari",
      "zh-CN": "每日限额",
      "zh-TW": "每日限額",
      hr: "Dnevni limit",
      cs: "Denní limit",
      da: "Daglig grænse",
      nl: "Dagelijkse limiet",
      en: "Daily Limit",
      fi: "Päivittäinen raja",
      fr: "Limite quotidienne",
      de: "Tageslimit",
      el: "Ημερήσιο Όριο",
      he: "מגבלה יומית",
      hi: "दैनिक सीमा",
      hu: "Napi limit",
      id: "Batas Harian",
      it: "Limite giornaliero",
      ja: "1日あたりの制限",
      ko: "일일 한도",
      ms: "Had Harian",
      no: "Daglig grense",
      pl: "Limit dzienny",
      pt: "Limite Diário",
      ro: "Limită zilnică",
      ru: "Дневной лимит",
      sk: "Denný limit",
      es: "Límite diario",
      sv: "Daglig gräns",
      th: "ขีดจำกัดรายวัน",
      tr: "Günlük Limit",
      uk: "Денний ліміт",
      vi: "Giới hạn hàng ngày",
    },
    id: "socialFocus_daily_limit",
    defaultValue: "noLimit",
    selects: [
      {
        name: {
          ar: "بلا حدود",
          ca: "Sense límits",
          "zh-CN": "没有限制",
          "zh-TW": "沒有限制",
          hr: "Bez ograničenja",
          cs: "Bez omezení",
          da: "Ingen grænser",
          nl: "Geen grenzen",
          en: "No Limits",
          fi: "Ei rajoja",
          fr: "Aucune limite",
          de: "Keine Grenzen",
          el: "Χωρίς όρια",
          he: "ללא גבולות",
          hi: "असीम",
          hu: "Nincs határ",
          id: "Tanpa Batas",
          it: "Nessun limite",
          ja: "制限なし",
          ko: "한계 없음",
          ms: "Tiada Had",
          no: "Ingen grenser",
          pl: "Bez ograniczeń",
          pt: "Sem Limites",
          ro: "Fără limite",
          ru: "Без ограничений",
          sk: "Žiadne limity",
          es: "Sin límites",
          sv: "Inga gränser",
          th: "ไม่มีขีดจำกัด",
          tr: "Sınır Yok",
          uk: "Без обмежень",
          vi: "Không có giới hạn",
        },
        id: "noLimit",
      },
    ],
  },
  {
    type: "checkbox",
    name: {
      ar: "عرض الموقت على الموقع",
      ca: "Mostra el temporitzador al lloc",
      "zh-CN": "现场显示计时器",
      "zh-TW": "現場顯示計時器",
      hr: "Prikaz mjerača vremena na licu mjesta",
      cs: "Zobrazit časovač na místě",
      da: "Vis timer på stedet",
      nl: "Timer op locatie weergeven",
      en: "Display Timer On Site",
      fi: "Näytä ajastin paikan päällä",
      fr: "Afficher la minuterie sur site",
      de: "Timer vor Ort anzeigen",
      el: "Εμφάνιση χρονοδιακόπτη στον ιστότοπο",
      he: "הצגת טיימר באתר",
      hi: "साइट पर टाइमर प्रदर्शित करें",
      hu: "Időzítő megjelenítése a helyszínen",
      id: "Tampilkan Timer Di Situs",
      it: "Visualizza il timer sul sito",
      ja: "オンサイトでタイマーを表示",
      ko: "사이트에 타이머 표시",
      ms: "Paparkan Pemasa Di Tapak",
      no: "Vis timer på stedet",
      pl: "Wyświetl timer na miejscu",
      pt: "Exibir temporizador no local",
      ro: "Afișează cronometrul la fața locului",
      ru: "Отображение таймера на месте",
      sk: "Zobraziť časovač na mieste",
      es: "Mostrar temporizador en el sitio",
      sv: "Visa timer på plats",
      th: "แสดงตัวจับเวลาบนเว็บไซต์",
      tr: "Zamanlayıcıyı Sitede Görüntüle",
      uk: "Відображення таймера на сайті",
      vi: "Hiển thị bộ đếm thời gian trên trang web",
    },
    id: "socialFocus_hacker-news_daily_limit_show_timer",
    defaultValue: false,
  },
];

const hackerNewsMobileGroups_Navigation = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'جديد'",
      ca: "Amaga 'Nou'",
      "zh-CN": "隐藏“新”",
      "zh-TW": "隱藏“新”",
      hr: "Sakrij 'Novo'",
      cs: "Skrýt 'Nové'",
      da: "Skjul 'Ny'",
      nl: "Verberg 'Nieuw'",
      en: "Hide 'New'",
      fi: "Piilota 'Uusi'",
      fr: "Masquer 'Nouveau'",
      de: "„Neu“ ausblenden",
      el: "Απόκρυψη 'Νέου'",
      he: "הסתר 'חדש'",
      hi: "'नया' छुपाएं",
      hu: "'Új' elrejtése",
      id: "Sembunyikan 'Baru'",
      it: "Nascondi 'Nuovo'",
      ja: "「新規」を隠す",
      ko: "'신규' 숨기기",
      ms: "Sembunyikan 'Baharu'",
      no: "Skjul 'Ny'",
      pl: "Ukryj „Nowy”",
      pt: "Ocultar 'Novo'",
      ro: "Ascunde „Nou”",
      ru: "Скрыть «Новое»",
      sk: "Skryť 'Nové'",
      es: "Ocultar 'Nuevo'",
      sv: "Göm 'Ny'",
      th: "ซ่อน 'ใหม่'",
      tr: "'Yeni'yi gizle",
      uk: "Сховати 'Новий'",
      vi: "Ẩn 'Mới'",
    },
    id: "socialFocus_hacker-news_hide_new",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'الماضي'",
      ca: "Amaga 'Passat'",
      "zh-CN": "隐藏“过去”",
      "zh-TW": "隱藏“過去”",
      hr: "Sakrij 'Prošlost'",
      cs: "Skrýt 'minulost'",
      da: "Skjul 'fortid'",
      nl: "Verberg 'Verleden'",
      en: "Hide 'Past'",
      fi: "Piilota 'menneisyys'",
      fr: "Masquer 'Passé'",
      de: "„Vergangenheit“ ausblenden",
      el: "Απόκρυψη 'Παρελθόν'",
      he: "הסתר 'עבר'",
      hi: "'अतीत' छिपाएँ",
      hu: "'Múlt' elrejtése",
      id: "Sembunyikan 'Masa Lalu'",
      it: "Nascondi 'Passato'",
      ja: "「過去」を隠す",
      ko: "'과거' 숨기기",
      ms: "Sembunyikan 'Lalu'",
      no: "Skjul 'Fortid'",
      pl: "Ukryj „przeszłość”",
      pt: "Ocultar 'Passado'",
      ro: "Ascunde „Trecut”",
      ru: "Скрыть «Прошлое»",
      sk: "Skryť 'minulosť'",
      es: "Ocultar 'Pasado'",
      sv: "Göm 'förflutna'",
      th: "ซ่อน 'อดีต'",
      tr: "'Geçmiş'i gizle",
      uk: "Приховати 'Минуле'",
      vi: "Ẩn 'Quá khứ'",
    },
    id: "socialFocus_hacker-news_hide_past",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'التعليقات'",
      ca: "Amaga 'Comentaris'",
      "zh-CN": "隐藏“评论”",
      "zh-TW": "隱藏“評論”",
      hr: "Sakrij 'Komentare'",
      cs: "Skrýt 'Komentáře'",
      da: "Skjul 'Kommentarer'",
      nl: "Verberg 'Opmerkingen'",
      en: "Hide 'Comments'",
      fi: "Piilota 'kommentit'",
      fr: "Masquer les 'Commentaires'",
      de: "„Kommentare“ ausblenden",
      el: "Απόκρυψη 'Σχόλια'",
      he: "הסתר 'תגובות'",
      hi: "'टिप्पणियाँ' छिपाएँ",
      hu: "'Megjegyzések' elrejtése",
      id: "Sembunyikan 'Komentar'",
      it: "Nascondi 'Commenti'",
      ja: "「コメント」を非表示にする",
      ko: "'댓글' 숨기기",
      ms: "Sembunyikan 'Ulasan'",
      no: "Skjul 'Kommentarer'",
      pl: "Ukryj „Komentarze”",
      pt: "Ocultar 'Comentários'",
      ro: "Ascunde „Comentarii”",
      ru: "Скрыть «Комментарии»",
      sk: "Skryť 'Komentáre'",
      es: "Ocultar 'Comentarios'",
      sv: "Dölj 'Kommentarer'",
      th: "ซ่อน 'ความคิดเห็น'",
      tr: "'Yorumlar'ı gizle",
      uk: "Приховати 'Коментарі'",
      vi: "Ẩn 'Bình luận'",
    },
    id: "socialFocus_hacker-news_hide_comments",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'اسأل'",
      ca: "Amaga 'Preguntar'",
      "zh-CN": "隐藏“询问”",
      "zh-TW": "隱藏“詢問”",
      hr: "Sakrij 'Pitaj'",
      cs: "Skrýt 'Zeptejte se'",
      da: "Skjul 'Spørg'",
      nl: "Verberg 'Vraag'",
      en: "Hide 'Ask'",
      fi: "Piilota 'Kysy'",
      fr: "Masquer 'Demander'",
      de: "„Fragen“ ausblenden",
      el: "Απόκρυψη 'Ρωτήστε'",
      he: "הסתר 'שאל'",
      hi: "'पूछें' छुपाएं",
      hu: "„Kérdés” elrejtése",
      id: "Sembunyikan 'Tanya'",
      it: "Nascondi 'Chiedi'",
      ja: "「質問」を非表示にする",
      ko: "'질문' 숨기기",
      ms: "Sembunyikan 'Tanya'",
      no: "Skjul 'Spør'",
      pl: "Ukryj „Zapytaj”",
      pt: "Ocultar 'Perguntar'",
      ro: "Ascunde „Întreabă”",
      ru: "Скрыть «Спросить»",
      sk: "Skryť 'Spýtať sa'",
      es: "Ocultar 'Preguntar'",
      sv: "Dölj 'Fråga'",
      th: "ซ่อน 'ถาม'",
      tr: "'Sor'u gizle",
      uk: "Сховати 'Запитати'",
      vi: "Ẩn 'Hỏi'",
    },
    id: "socialFocus_hacker-news_hide_ask",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'إظهار'",
      ca: "Amaga 'Mostra'",
      "zh-CN": "隐藏“显示”",
      "zh-TW": "隱藏“顯示”",
      hr: "Sakrij 'Prikaži'",
      cs: "Skrýt 'Zobrazit'",
      da: "Skjul 'Vis'",
      nl: "Verberg 'Toon'",
      en: "Hide 'Show'",
      fi: "Piilota 'Näytä'",
      fr: "Masquer 'Afficher'",
      de: "Ausblenden „Anzeigen“",
      el: "Απόκρυψη 'Εμφάνιση'",
      he: "הסתר 'הצג'",
      hi: "छिपाएं दिखाएं'",
      hu: "'Megjelenítés' elrejtése",
      id: "Sembunyikan 'Tampilkan'",
      it: "Nascondi 'Mostra'",
      ja: "「表示」を隠す",
      ko: "'표시' 숨기기",
      ms: "Sembunyikan 'Tunjukkan'",
      no: "Skjul 'Vis'",
      pl: "Ukryj „Pokaż”",
      pt: "Ocultar 'Mostrar'",
      ro: "Ascunde „Afișează”",
      ru: "Скрыть «Показать»",
      sk: "Skryť 'Zobraziť'",
      es: "Ocultar 'Mostrar'",
      sv: "Dölj 'Visa'",
      th: "ซ่อน 'แสดง'",
      tr: "'Göster'i gizle",
      uk: "Сховати 'Показати'",
      vi: "Ẩn 'Hiển thị'",
    },
    id: "socialFocus_hacker-news_hide_show",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'الوظائف'",
      ca: "Amaga 'Ocupacions'",
      "zh-CN": "隐藏“职位”",
      "zh-TW": "隱藏“職位”",
      hr: "Sakrij 'Poslove'",
      cs: "Skrýt 'Zaměstnání'",
      da: "Skjul 'Jobs'",
      nl: "Verberg 'Vacatures'",
      en: "Hide 'Jobs'",
      fi: "Piilota 'Työt'",
      fr: "Masquer les « Emplois »",
      de: "„Jobs“ ausblenden",
      el: "Απόκρυψη 'Εργασίες'",
      he: "הסתר 'עבודות'",
      hi: "'नौकरियाँ' छिपाएँ",
      hu: "'Munkák' elrejtése",
      id: "Sembunyikan 'Pekerjaan'",
      it: "Nascondi 'Lavori'",
      ja: "「ジョブ」を非表示にする",
      ko: "'채용정보' 숨기기",
      ms: "Sembunyikan 'Pekerjaan'",
      no: "Skjul 'Jobber'",
      pl: "Ukryj „Pracę”",
      pt: "Ocultar 'Trabalhos'",
      ro: "Ascundeți „Locuri de muncă”",
      ru: "Скрыть «Вакансии»",
      sk: "Skryť 'Úlohy'",
      es: "Ocultar 'Trabajos'",
      sv: "Dölj 'Jobb'",
      th: "ซ่อน 'งาน'",
      tr: "'İşler'i gizle",
      uk: "Приховати 'Вакансії'",
      vi: "Ẩn 'Việc làm'",
    },
    id: "socialFocus_hacker-news_hide_jobs",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء 'إرسال'",
      ca: "Amaga 'Envia'",
      "zh-CN": "隐藏“提交”",
      "zh-TW": "隱藏“提交”",
      hr: "Sakrij 'Pošalji'",
      cs: "Skrýt 'Odeslat'",
      da: "Skjul 'Send'",
      nl: "Verberg 'Verzenden'",
      en: "Hide 'Submit'",
      fi: "Piilota 'Lähetä'",
      fr: "Masquer 'Envoyer'",
      de: "„Senden“ ausblenden",
      el: "Απόκρυψη 'Υποβολή'",
      he: "הסתר 'שלח'",
      hi: "'सबमिट करें' छुपाएं",
      hu: "„Küldés” elrejtése",
      id: "Sembunyikan 'Kirim'",
      it: "Nascondi 'Invia'",
      ja: "「送信」を非表示にする",
      ko: "'제출' 숨기기",
      ms: "Sembunyikan 'Serah'",
      no: "Skjul 'Send inn'",
      pl: "Ukryj „Prześlij”",
      pt: "Ocultar 'Enviar'",
      ro: "Ascunde „Trimite”",
      ru: "Скрыть «Отправить»",
      sk: "Skryť 'Odoslať'",
      es: "Ocultar 'Enviar'",
      sv: "Dölj 'Skicka'",
      th: "ซ่อน 'ส่ง'",
      tr: "'Gönder'i gizle",
      uk: "Сховати 'Надіслати'",
      vi: "Ẩn 'Gửi'",
    },
    id: "socialFocus_hacker-news_hide_submit",
    defaultValue: false,
  },
];

const hackerNewsMobileGroups_Post = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء المجال",
      ca: "Amaga el domini",
      "zh-CN": "隐藏域名",
      "zh-TW": "隱藏域名",
      hr: "Sakrij domenu",
      cs: "Skrýt doménu",
      da: "Skjul domæne",
      nl: "Domein verbergen",
      en: "Hide Domain",
      fi: "Piilota verkkotunnus",
      fr: "Masquer le domaine",
      de: "Domäne ausblenden",
      el: "Απόκρυψη τομέα",
      he: "הסתר דומיין",
      hi: "डोमेन छिपाएँ",
      hu: "Domain elrejtése",
      id: "Sembunyikan Domain",
      it: "Nascondi dominio",
      ja: "ドメインを隠す",
      ko: "도메인 숨기기",
      ms: "Sembunyikan Domain",
      no: "Skjul domene",
      pl: "Ukryj domenę",
      pt: "Ocultar domínio",
      ro: "Ascunde domeniul",
      ru: "Скрыть домен",
      sk: "Skryť doménu",
      es: "Ocultar dominio",
      sv: "Dölj domän",
      th: "ซ่อนโดเมน",
      tr: "Alanı Gizle",
      uk: "Приховати домен",
      vi: "Ẩn tên miền",
    },
    id: "socialFocus_hacker-news_post_hide_domain",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'التصويت'",
      ca: "Amaga el botó 'Vota'",
      "zh-CN": "隐藏“投票”按钮",
      "zh-TW": "隱藏“投票”按鈕",
      hr: "Sakrij gumb 'Glasaj'",
      cs: "Skrýt tlačítko „Hlasovat“",
      da: "Skjul 'Stem'-knap",
      nl: "Knop 'Stem' verbergen",
      en: "Hide 'Vote' Button",
      fi: "Piilota Äänestyspainike",
      fr: "Masquer le bouton « Voter »",
      de: "Schaltfläche „Abstimmen“ ausblenden",
      el: "Απόκρυψη του κουμπιού «ψηφοφορία»",
      he: "הסתר את כפתור 'הצבע'",
      hi: "'वोट' बटन छिपाएँ",
      hu: "A „Szavazás” gomb elrejtése",
      id: "Sembunyikan Tombol 'Pilih'",
      it: "Nascondi il pulsante 'Vota'",
      ja: "「投票」ボタンを非表示にする",
      ko: "'투표' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Undi'",
      no: "Skjul Stem-knappen",
      pl: "Ukryj przycisk „Głosuj”",
      pt: "Ocultar botão 'Votar'",
      ro: "Ascundeți butonul „Votați”",
      ru: "Скрыть кнопку «Голосовать»",
      sk: "Skryť tlačidlo „Hlasovať“",
      es: "Ocultar el botón 'Votar'",
      sv: "Dölj 'Rösta'-knappen",
      th: "ซ่อนปุ่ม 'โหวต'",
      tr: "'Oy Ver' Düğmesini Gizle",
      uk: "Сховати кнопку «Голосувати»",
      vi: "Ẩn nút 'Bình chọn'",
    },
    id: "socialFocus_hacker-news_post_hide_vote_button",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'إخفاء'",
      ca: "Amaga el botó 'Oculta'",
      "zh-CN": "隐藏“隐藏”按钮",
      "zh-TW": "隱藏“隱藏”按鈕",
      hr: "Sakrij gumb 'Sakrij'",
      cs: "Skrýt tlačítko 'Skrýt'",
      da: "Skjul 'Skjul'-knap",
      nl: "Knop 'Verbergen' verbergen",
      en: "Hide 'Hide' Button",
      fi: "Piilota Piilota-painike",
      fr: "Masquer le bouton « Masquer »",
      de: "Schaltfläche „Ausblenden“ ausblenden",
      el: "Κουμπί απόκρυψης 'Απόκρυψη'",
      he: "הסתר כפתור 'הסתר'",
      hi: "'छिपाएँ' बटन छिपाएँ",
      hu: "Az „Elrejtés” gomb elrejtése",
      id: "Sembunyikan Tombol 'Sembunyikan'",
      it: "Nascondi il pulsante 'Nascondi'",
      ja: "「非表示」ボタンを非表示にする",
      ko: "'숨기기' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Sembunyikan'",
      no: "Skjul 'Skjul'-knappen",
      pl: "Ukryj przycisk „Ukryj”",
      pt: "Ocultar botão 'Ocultar'",
      ro: "Ascunde butonul „Ascunde”",
      ru: "Скрыть кнопку «Скрыть»",
      sk: "Skryť tlačidlo „Skryť“",
      es: "Ocultar el botón 'Ocultar'",
      sv: "Göm 'Göm'-knappen",
      th: "ซ่อนปุ่ม 'ซ่อน'",
      tr: "'Gizle' Düğmesini Gizle",
      uk: "Приховати кнопку «Приховати»",
      vi: "Ẩn nút 'Ẩn'",
    },
    id: "socialFocus_hacker-news_post_hide_hide_button",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء عدد النقاط",
      ca: "Amaga el recompte de punts",
      "zh-CN": "隐藏点数",
      "zh-TW": "隱藏點數",
      hr: "Sakrij broj bodova",
      cs: "Skrýt počet bodů",
      da: "Skjul antal point",
      nl: "Puntentelling verbergen",
      en: "Hide Points Count",
      fi: "Piilota pisteiden määrä",
      fr: "Masquer le décompte des points",
      de: "Punkteanzahl ausblenden",
      el: "Απόκρυψη καταμέτρησης πόντων",
      he: "הסתר ספירת נקודות",
      hi: "अंक गिनती छिपाएँ",
      hu: "Pontszám elrejtése",
      id: "Sembunyikan Jumlah Poin",
      it: "Nascondi conteggio punti",
      ja: "ポイント数を非表示にする",
      ko: "포인트 수 숨기기",
      ms: "Sembunyikan Kiraan Mata",
      no: "Skjul antall poeng",
      pl: "Ukryj liczbę punktów",
      pt: "Ocultar contagem de pontos",
      ro: "Ascunde numărul de puncte",
      ru: "Скрыть подсчет очков",
      sk: "Skryť počet bodov",
      es: "Ocultar recuento de puntos",
      sv: "Göm antal poäng",
      th: "ซ่อนการนับคะแนน",
      tr: "Puan Sayısını Gizle",
      uk: "Приховати кількість балів",
      vi: "Ẩn số điểm",
    },
    id: "socialFocus_hacker-news_post_hide_points_count",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء الوقت",
      ca: "Amaga el temps",
      "zh-CN": "隐藏时间",
      "zh-TW": "隱藏時間",
      hr: "Sakrij vrijeme",
      cs: "Skrýt čas",
      da: "Skjul tid",
      nl: "Tijd verbergen",
      en: "Hide Time",
      fi: "Piilota aika",
      fr: "Masquer l'heure",
      de: "Zeit ausblenden",
      el: "Απόκρυψη χρόνου",
      he: "הסתר זמן",
      hi: "समय छिपाएँ",
      hu: "Idő elrejtése",
      id: "Sembunyikan Waktu",
      it: "Nascondi tempo",
      ja: "時間を隠す",
      ko: "시간 숨기기",
      ms: "Sembunyikan Masa",
      no: "Skjul tid",
      pl: "Ukryj czas",
      pt: "Ocultar tempo",
      ro: "Ascunde Timpul",
      ru: "Скрыть время",
      sk: "Skryť čas",
      es: "Ocultar hora",
      sv: "Göm tid",
      th: "ซ่อนเวลา",
      tr: "Zamanı Gizle",
      uk: "Приховати час",
      vi: "Ẩn thời gian",
    },
    id: "socialFocus_hacker-news_post_hide_time",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء زر 'التعليقات'",
      ca: "Amaga el botó 'Comentaris'",
      "zh-CN": "隐藏“评论”按钮",
      "zh-TW": "隱藏“評論”按鈕",
      hr: "Sakrij gumb 'Komentari'",
      cs: "Skrýt tlačítko 'Komentáře'",
      da: "Skjul knappen 'Kommentarer'",
      nl: "Knop 'Opmerkingen' verbergen",
      en: "Hide 'Comments' Button",
      fi: "Piilota Kommentit-painike",
      fr: "Masquer le bouton « Commentaires »",
      de: "Schaltfläche „Kommentare“ ausblenden",
      el: "Κουμπί απόκρυψη «Σχόλια»",
      he: "הסתר את לחצן 'הערות'",
      hi: "'टिप्पणियाँ' बटन छिपाएँ",
      hu: "A 'Megjegyzések' gomb elrejtése",
      id: "Sembunyikan Tombol 'Komentar'",
      it: "Nascondi il pulsante 'Commenti'",
      ja: "「コメント」ボタンを非表示にする",
      ko: "'댓글' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Ulasan'",
      no: "Skjul 'Kommentarer'-knappen",
      pl: "Ukryj przycisk „Komentarze”",
      pt: "Ocultar botão 'Comentários'",
      ro: "Ascundeți butonul „Comentarii”",
      ru: "Скрыть кнопку «Комментарии»",
      sk: "Skryť tlačidlo 'Komentáre'",
      es: "Ocultar el botón 'Comentarios'",
      sv: "Dölj knappen 'Kommentarer'",
      th: "ซ่อนปุ่ม 'ความคิดเห็น'",
      tr: "'Yorumlar' Düğmesini Gizle",
      uk: "Приховати кнопку «Коментарі»",
      vi: "Ẩn nút 'Nhận xét'",
    },
    id: "socialFocus_hacker-news_post_hide_comments_button",
    defaultValue: false,
  },
];

const hackerNewsMobileGroups_Comments = [
  {
    type: "checkbox",
    name: {
      ar: "إخفاء التعليقات",
      ca: "Amaga els comentaris",
      "zh-CN": "隐藏评论",
      "zh-TW": "隱藏評論",
      hr: "Sakrij komentare",
      cs: "Skrýt komentáře",
      da: "Skjul kommentarer",
      nl: "Opmerkingen verbergen",
      en: "Hide Comments",
      fi: "Piilota kommentit",
      fr: "Masquer les commentaires",
      de: "Kommentare ausblenden",
      el: "Απόκρυψη σχολίων",
      he: "הסתר הערות",
      hi: "टिप्पणियाँ छिपाएँ",
      hu: "Megjegyzések elrejtése",
      id: "Sembunyikan Komentar",
      it: "Nascondi commenti",
      ja: "コメントを隠す",
      ko: "댓글 숨기기",
      ms: "Sembunyikan Komen",
      no: "Skjul kommentarer",
      pl: "Ukryj komentarze",
      pt: "Ocultar comentários",
      ro: "Ascunde comentariile",
      ru: "Скрыть комментарии",
      sk: "Skryť komentáre",
      es: "Ocultar comentarios",
      sv: "Dölj kommentarer",
      th: "ซ่อนความคิดเห็น",
      tr: "Yorumları Gizle",
      uk: "Приховати коментарі",
      vi: "Ẩn bình luận",
    },
    id: "socialFocus_hacker-news_comments_hide_comments",
    defaultValue: false,
  },
  {
    type: "checkbox",
    name: {
      ar: "إخفاء أزرار 'الرد'",
      ca: "Amaga els botons 'Resposta'",
      "zh-CN": "隐藏“回复”按钮",
      "zh-TW": "隱藏「回覆」按鈕",
      hr: "Sakrij gumbe 'Odgovori'",
      cs: "Skrýt tlačítka „Odpovědět“",
      da: "Skjul 'Svar'-knapper",
      nl: "Verberg de 'Beantwoord'-knoppen",
      en: "Hide 'Reply' Buttons",
      fi: "Piilota Vastaa-painikkeet",
      fr: "Masquer les boutons « Répondre »",
      de: "Schaltflächen „Antworten“ ausblenden",
      el: "Απόκρυψη κουμπιών «Απάντηση»",
      he: "הסתר את לחצני 'השב'",
      hi: "'उत्तर' बटन छिपाएँ",
      hu: "A „Válasz” gombok elrejtése",
      id: "Sembunyikan Tombol 'Balas'",
      it: "Nascondi i pulsanti 'Rispondi'",
      ja: "「返信」ボタンを非表示にする",
      ko: "'답장' 버튼 숨기기",
      ms: "Sembunyikan Butang 'Balas'",
      no: "Skjul 'Svar'-knapper",
      pl: "Ukryj przyciski „Odpowiedz”",
      pt: "Ocultar botões de ‘Responder’",
      ro: "Ascundeți butoanele „Răspuns”",
      ru: "Скрыть кнопки «Ответить»",
      sk: "Skryť tlačidlá „Odpovedať“",
      es: "Ocultar botones 'Responder'",
      sv: "Dölj 'Svara'-knappar",
      th: "ซ่อนปุ่ม 'ตอบกลับ'",
      tr: "'Yanıtla' Düğmelerini Gizle",
      uk: "Сховати кнопки «Відповісти»",
      vi: "Ẩn nút 'Trả lời'",
    },
    id: "socialFocus_hacker-news_comments_hide_reply_buttons",
    defaultValue: false,
  },
];

// MARK: - Mobile Builder

const hackerNewsMobileGroups = [
  {
    groupName: {
      ar: "",
      ca: "",
      "zh-CN": "",
      "zh-TW": "",
      hr: "",
      cs: "",
      da: "",
      nl: "",
      en: "",
      fi: "",
      fr: "",
      de: "",
      el: "",
      he: "",
      hi: "",
      hu: "",
      id: "",
      it: "",
      ja: "",
      ko: "",
      ms: "",
      no: "",
      pl: "",
      pt: "",
      ro: "",
      ru: "",
      sk: "",
      es: "",
      sv: "",
      th: "",
      tr: "",
      uk: "",
      vi: "",
    },
    groupId: "disableSocialFocus",
    parentCategoryId: "hackerNews",
    options: [hackerNewsMobileGroups_DisableSocialFocus],
  },
  {
    groupName: {
      ar: "أساسيات",
      ca: "Essencials",
      "zh-CN": "必需品",
      "zh-TW": "必需品",
      hr: "Osnove",
      cs: "Essentials",
      da: "Essentialer",
      nl: "Essentiële zaken",
      en: "Essentials",
      fi: "Essentials",
      fr: "Essentiel",
      de: "Wesentliches",
      el: "Βασικά",
      he: "יסודות",
      hi: "अनिवार्य",
      hu: "Essentials",
      id: "Penting",
      it: "Elementi essenziali",
      ja: "必需品",
      ko: "골자",
      ms: "Perkara-perkara penting",
      no: "Essensielle",
      pl: "Elementy zasadnicze",
      pt: "Fundamentos",
      ro: "Esențiale",
      ru: "Основы",
      sk: "Essentials",
      es: "Esenciales",
      sv: "Essentials",
      th: "สิ่งจำเป็น",
      tr: "Temeller",
      uk: "Основи",
      vi: "Yếu tố cần thiết",
    },
    groupId: "essentials",
    parentCategoryId: "hackerNews",
    options: hackerNewsMobileGroups_Essentials,
  },
  {
    groupName: {
      ar: "الحد الزمني",
      ca: "Límit de temps",
      "zh-CN": "时限",
      "zh-TW": "時限",
      hr: "Vremensko ograničenje",
      cs: "Časový limit",
      da: "Tidsgrænse",
      nl: "Tijdslimiet",
      en: "Time Limit",
      fi: "Määräaika",
      fr: "Limite de temps",
      de: "Zeitlimit",
      el: "Προθεσμία",
      he: "מגבלת זמן",
      hi: "समय सीमा",
      hu: "Időkorlát",
      id: "Batas waktu",
      it: "Limite di tempo",
      ja: "期限",
      ko: "시간 제한",
      ms: "Had Masa",
      no: "Tidsbegrensning",
      pl: "Limit czasu",
      pt: "Limite de tempo",
      ro: "Limită de timp",
      ru: "Лимит времени",
      sk: "Časový limit",
      es: "Límite de tiempo",
      sv: "Tidsgräns",
      th: "จำกัดเวลา",
      tr: "Zaman Sınırı",
      uk: "Обмеження часу",
      vi: "Giới hạn thời gian",
    },
    groupId: "timeLimit",
    parentCategoryId: "hackerNews",
    options: hackerNewsMobileGroups_TimeLimit,
  },
  {
    groupName: {
      ar: "ملاحة",
      ca: "Navegació",
      "zh-CN": "导航",
      "zh-TW": "導航",
      hr: "Navigacija",
      cs: "Navigace",
      da: "Navigation",
      nl: "Navigatie",
      en: "Navigation",
      fi: "Navigointi",
      fr: "Navigation",
      de: "Navigation",
      el: "Πλοήγηση",
      he: "ניווט",
      hi: "मार्गदर्शन",
      hu: "Navigáció",
      id: "Navigasi",
      it: "Navigazione",
      ja: "ナビゲーション",
      ko: "항해",
      ms: "Navigasi",
      no: "Navigasjon",
      pl: "Nawigacja",
      pt: "Navegação",
      ro: "Navigare",
      ru: "Навигация",
      sk: "Navigácia",
      es: "Navegación",
      sv: "Navigering",
      th: "การนำทาง",
      tr: "Navigasyon",
      uk: "Навігація",
      vi: "Điều hướng",
    },
    groupId: "navigation",
    parentCategoryId: "hacker-news",
    options: hackerNewsMobileGroups_Navigation,
  },
  {
    groupName: {
      ar: "دعامات",
      ca: "Publicacions",
      "zh-CN": "帖子",
      "zh-TW": "貼文",
      hr: "Postovi",
      cs: "Příspěvky",
      da: "Indlæg",
      nl: "Berichten",
      en: "Posts",
      fi: "Viestit",
      fr: "Des postes",
      de: "Beiträge",
      el: "Αναρτήσεις",
      he: "פוסטים",
      hi: "पदों",
      hu: "Hozzászólások",
      id: "Postingan",
      it: "Messaggi",
      ja: "投稿",
      ko: "게시물",
      ms: "Catatan",
      no: "Innlegg",
      pl: "Posty",
      pt: "Postagens",
      ro: "Postări",
      ru: "Сообщения",
      sk: "Príspevky",
      es: "Publicaciones",
      sv: "Inlägg",
      th: "กระทู้",
      tr: "Gönderiler",
      uk: "Пости",
      vi: "Bài viết",
    },
    groupId: "post",
    parentCategoryId: "hacker-news",
    options: hackerNewsMobileGroups_Post,
  },
  {
    groupName: {
      ar: "صفحة التعليقات",
      ca: "Pàgina de comentaris",
      "zh-CN": "评论页",
      "zh-TW": "評論頁",
      hr: "Stranica s komentarima",
      cs: "Stránka s komentáři",
      da: "Kommentarside",
      nl: "Opmerkingenpagina",
      en: "Comments Page",
      fi: "Kommentit-sivu",
      fr: "Page de commentaires",
      de: "Kommentarseite",
      el: "Σελίδα σχολίων",
      he: "עמוד תגובות",
      hi: "टिप्पणियाँ पृष्ठ",
      hu: "Megjegyzések oldal",
      id: "Halaman Komentar",
      it: "Pagina dei commenti",
      ja: "コメントページ",
      ko: "댓글 페이지",
      ms: "Halaman Komen",
      no: "Kommentarside",
      pl: "Strona z komentarzami",
      pt: "Página de comentários",
      ro: "Pagina de comentarii",
      ru: "Страница комментариев",
      sk: "Stránka s komentármi",
      es: "Página de comentarios",
      sv: "Kommentarssida",
      th: "หน้าความคิดเห็น",
      tr: "Yorumlar Sayfası",
      uk: "Сторінка коментарів",
      vi: "Trang bình luận",
    },
    groupId: "comments-page",
    parentCategoryId: "hacker-news",
    options: hackerNewsMobileGroups_Comments,
  },
];
